language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

install:
  - composer update -n --prefer-dist
  # pthreads is now only supported on PHP 7.2+
  - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then
      travis/install-pthreads.sh;
    fi
  - travis/install-parallel.sh;
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - ./coveralls.phar -v

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local
